#------------------------------------------------------------
# ComputeCanada: Graham + SLURM
#------------------------------------------------------------

# Cluster host and scheduler options: the defaults come from
# Graham at Compute Canada, running SLURM. Other options can
# be found in the library of snippets,
# `_includes/snippets_library`. To use one, replace options
# below with those in `_config_options.yml` from the
# library. E.g, to customise for Cirrus at EPCC, running
# PBS, we could replace the options below with those from
# 
# _includes/snippets_library/EPCC_Cirrus_pbs/_config_options.yml
# 
# If your cluster is not represented in the library, please
# copy an existing folder, rename it, and customize for your
# installation. Remember to keep the leading slash on the
# `snippets` variable below!

snippets: "/snippets_library/USask_Plato_slurm"

local:
  prompt: "[user@laptop ~]$"

remote:
  name: "Plato"
  login: "plato.usask.ca"
  host: "platolgn01"
  node: "plato310"
  location: "University of Saskatchewan"
  homedir: "/home"
  user: "nsid"
  prompt: "[nsid@platolgn01 ~]$"

sched:
  name: "SLURM"
  submit:
    name: "sbatch"
    options: ""
  queue:
    debug: "debug"
    testing: "testing"
  status: "squeue"
  flag:
    user: "-u nsid"
    interactive: ""
    histdetail: "-l -j"
    name: "-J"
    time: "-t"
    queue: "-p"
  del: "scancel"
  interactive: "srun"
  info: "sinfo"
  comment: "#SBATCH"
  hist: "sacct -u nsid"
